#undef DEBOUNCE
#define DEBOUNCE 5

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "eZrPW/Az4pY6"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 2

#define RGB_MATRIX_STARTUP_SPD 60

