#undef DEBOUNCE
#define DEBOUNCE 5

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "eZrPW/x9LAAx"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60
#define ACHORDION_STREAK
